# Generated by Django 4.0.5 on 2022-06-10 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_moringmerch_alter_article_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MoringMerch',
            new_name='MoringaMerch',
        ),
    ]
